### ISSUE TITLE
Is it OK to use ptr::read() instead of ptr::read_volatile() in SeqLock::read() ?

### ISSUE THREAD

**Issue by OneMore14** [Amanieu/seqlock#10]
Hi, I'm learning concurrency programming these days, just curious to know if it is OK to use ptr::read() below:

https://github.com/Amanieu/seqlock/blob/b72653fd9c38141da7e588a97a1b654239f5d4df/src/lib.rs#L136

when write operation finished, there is a `Release` ording here:
https://github.com/Amanieu/seqlock/blob/b72653fd9c38141da7e588a97a1b654239f5d4df/src/lib.rs#L90

And to read `seq1`, there is a `Acquire` ording:
https://github.com/Amanieu/seqlock/blob/b72653fd9c38141da7e588a97a1b654239f5d4df/src/lib.rs#L121

So these is a Release-Acquire relationship here, then we can get these conclusions:

1. if a write operation is completed before reading `seq1`, I think we can always get the latest value by using `ptr::read()` because the Release-Acquire relationship.
2. if a write operation is before reading `seq1`, but not finished when reading `seq1`,  then `seq1 & 1` would be 1, just retry.
3. if a write operation begins after reading `seq1`, then `seq1` must be different with `seq2`, then it's also ok to use `ptr::read()`.

I don't know if these conclusions are correct, hope to get some reviews, thanks in advance.

**Comment by Amanieu** [comment]
`volatile_read` must be used because the read side doesn't take a lock, which means it may race with a concurrent write. The core issue is that the read/write of the actual value isn't atomic and may be split into multiple read/write instructions. In the case of a race this could result in a "torn read" where half of the bytes come from the old value and half come from the new value. This is UB in Rust.

**Comment by OneMore14** [comment]
> The core issue is that the read/write of the actual value isn't atomic and may be split into multiple read/write instructions.

I understand this, but ```volatile_read``` isn't atomic either, so I'm still confused why we have to use ```volatile_read```?

And if there are concrruent reading/writing, ```seq1 == seq2``` must be false, then the "torn read" value will be discarded. It seems that users will never read an inconsistent value.

**Comment by Amanieu** [comment]
Because the compiler and its optimization passes fundamentally assume that a value read by a normal read doesn't change: reading the same memory location multiple times must always return the same value (at least until the next fence/atomic operation).

**Comment by OneMore14** [comment]
in ```end_write()```, atomic write to ```seq``` tagged ```Release```, in ```read()```, each loop atomic read ```seq``` tagged ```Acquire``` .  Shouldn't the ptr::read()  always read the newest value? or compiler will still do some optimizations in this situation?
