### ISSUE TITLE
cannot call non-const fn `parking_lot::lock_api::Mutex::<parking_lot::RawMutex, ()>::new` in constant functions

### ISSUE THREAD

**Issue by brooksprumo** [Amanieu/seqlock#8]
I found a use-case for seqlock in my repo where I had a Copy type—yay! I added seqlock, and replaced an RwLock with SeqLock. Unfortunately I hit this build error:

```
error[E0015]: cannot call non-const fn `parking_lot::lock_api::Mutex::<parking_lot::RawMutex, ()>::new` in constant functions
   --> /home/.cargo/registry/src/index.crates.io-6f17d22bba15001f/seqlock-0.2.0/src/lib.rs:101:20
    |
101 |             mutex: Mutex::new(()),
    |                    ^^^^^^^^^^^^^^
    |
    = note: calls in constant functions are limited to constant functions, tuple structs and tuple variants
```

I see that older versions of lock-api did *not* have `const` on `Mutext::new()`[^1], but now it does. Is there a good fix for this? I see that lock-api has a feature (`has_const_fn_trait_bound`) that sets the `const`-ness. Since seqlock does not depend on lock-api directly, but instead through parking_lot, I'm not sure what's the right way to handle this. Maybe there's something I can set on my end to resolve this though?

[^1]: https://docs.rs/lock_api/0.4.6/lock_api/struct.Mutex.html#method.new

**Comment by Amanieu** [comment]
If you update to the latest version of lock-api this is fixed. Just run `cargo update`.

**Comment by brooksprumo** [comment]
Thank you, that resolves my issue.
