### ISSUE TITLE
Possible memory order issue

### ISSUE THREAD

**Issue by AngelicosPhosphoros** [Amanieu/seqlock#9]
Hi!

I read a code of create and noticed this segment:
```rust
            // We need to use a volatile read here because the data may be
            // concurrently modified by a writer. We also use MaybeUninit in
            // case we read the data in the middle of a modification.
            let result = unsafe { ptr::read_volatile(self.data.get() as *mut MaybeUninit<T>) };

            // Make sure the seq2 read occurs after reading the data. What we
            // ideally want is a load(Release), but the Release ordering is not
            // available on loads.
            fence(Ordering::Acquire);

            // If the sequence number is the same then the data wasn't modified
            // while we were reading it, and can be returned.
            let seq2 = self.seq.load(Ordering::Relaxed);
            if seq1 == seq2 {
                return unsafe { result.assume_init() };
            }
```

Shouldn't fence here use `AcqRel`? While using Acquire indeed prevents moving second atomic load up, it doesn't prevent moving read_volatile down. So CPU may reorder your code like this:
```
seq1 = load_atomic;
seq2 = load_atomic;
if seq1 == seq2 {
   return load value; // This is valid for moving down because acquire doesn't prevent moving down.
}
```

**Comment by AngelicosPhosphoros** [comment]
Same thing with a fence here: https://github.com/Amanieu/seqlock/blob/b72653fd9c38141da7e588a97a1b654239f5d4df/src/lib.rs#L162
It doesn't prevent writes to the underlying memory from moving before updating an atomic.

It may be not noticed so far because x86-64 have a guaranteed store order but other platforms could do such moves.

IMHO, you should use AcqRel fences in both cases.

**Comment by Amanieu** [comment]
The code actually works, but it's a bit subtle. Essentially the `fence(Acquire)` is there to effectively give the volatile load "acquire" semantics. This ensures it always executes before the seq2 load.

**Comment by AngelicosPhosphoros** [comment]
But does volatile guarantee that CPU wouldn't reorder instructions? AFAIK, it only affects the compiler.

**Comment by Amanieu** [comment]
Volatile on its own doesn't guarantee this, that's what the fence is for.

**Comment by AngelicosPhosphoros** [comment]
Do I understand correctly that volatile read followed by a acquire fence hace same effect as acquire load, and therefore it would happen before any reads after fence?

**Comment by Amanieu** [comment]
It's a bit of a gray area in the language, but it works in practice. The proper solution is to use something like https://github.com/rust-lang/rfcs/pull/3301, but that doesn't exist in the language yet.

**Comment by AngelicosPhosphoros** [comment]
Thank you for answering my questions.
